trigger:
  - main

pool: Skin Explorer Model Agents

steps:
  - task: Cache@2
    inputs:
      key: 'lolfiles'
      path: 'game'
      
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.10"
      addToPath: true
      architecture: "x64"
    displayName: "Use Python 3.10"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - task: PythonScript@0
    inputs:
      scriptSource: "filePath"
      scriptPath: "1-download-game-files.py"
    displayName: "Download game files"
