trigger:
  - main

pool: Skin Explorer Model Agents

variables:
  - name: game-files-version
    value: ""
  - name: game-files-manifest
    value: ""

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.10"
      addToPath: true
      architecture: "x64"
    displayName: "Use Python 3.10"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - task: PythonScript@0
    inputs:
      scriptSource: "filePath"
      scriptPath: "1-read-latest-version.py"
    displayName: "Read latest (PBE) version"

  - task: PythonScript@0
    inputs:
      scriptSource: "filePath"
      scriptPath: "2-download-game-files.py"
    displayName: "Download game files"
