trigger:
  - main

variables:
  - group: skin-explorer-models
  - name: GAME_FILES_MANIFEST
    value: ""

jobs:
  - job: ETL
    pool: Skin Explorer Worker
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.10"
          addToPath: true
          architecture: "x64"
        displayName: "Use Python 3.10"

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - task: PythonScript@0
        inputs:
          scriptSource: "filePath"
          scriptPath: "1-download-game-files.py"
        displayName: "Download game files and extract models"
